### ISSUE TITLE
Proposal Questions

### ISSUE THREAD

**Issue by spiffmon** [gitamohr/USD-proposals#1]
1. In light of the recent schema versioning work, I think the `isa` and `hasAPI` predicates should be documented to take something like a `asFamily=true` (can debate the default value), such that the given `typeName` arguments are interpreted as schema _family_ names rather than typeNames.
2.  On [this example](https://github.com/gitamohr/USD-proposals/blob/main/proposals/pattern-based-collections/README.md?plain=1#L44), should it not be 'on prims whose name or an ancestor prim's name starts with "Robot"' ? If not, I do not understand what "//." signifies?
3. Either where you introduce the `expression` attribute addition to CollectionAPI, or in the **USD Support** section, please state the proposed collection evaluation logic, i.e. are we unioning expression with includes/excludes/includeRoot rels?

**Comment by gitamohr** [comment]
1. Oh wow, yeah it looks like there are 3 flavors of `isa`, _6_ of `hasAPI`, and **_8_** of `hasAPIInFamily` to handle at least?
2. Good catch, thank you!
3. Yes another good catch, thank you!

**Comment by spiffmon** [comment]
Regarding #1, In the interest of getting the proposal out, I'll suggest that for now we don't modify your example, but explain that we will refine those queries to support schema versioning... and possibly update the proposal.

I don't think that needs to gate "approval" of the work, and I _also_ am unsure we need to expose the full complexity of the C++ API's.  So let's have some internal discussions about where the sweet spot may be here?

**Comment by gitamohr** [comment]
I agree -- it seems like a sizable conceptual hurdle to just throw it all out there.
